import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Providers } from "../redux/Provider"


const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"], 
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <main>
            <Sidebar />
            <div className="children-wrapper ml-[22rem] ">
              <Navbar />
              {children}
              {/* footer */}
              <Footer />
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
